export { createSshClient, type SshClient } from './ssh-client'
export { createMutagenSyncManager, type SyncManager, checkMutagenInstalled } from './mutagen-sync'
export { createRemoteTools } from './tools'
export { initializeRemote } from './init'
export type { RemoteInitResult } from './init'
export { processRemoteCommand } from './state'
